//
//  Constants.swift
//  Alias
//
//  Created by  Даниил Хомяков on 18.08.2024.
//

import Foundation

struct Constants {
    
    static let teamNames = [
        "Word Warriors",
        "Verbal Ninjas",
        "Speedy Speakers",
        "The Quick Thinkers",
        "Brainstormers",
        "Rapid Riddlers",
        "The Clue Crew",
        "Talk Titans",
        "Master Mimics",
        "Synonym Squad",
        "Express Experts",
        "Puzzle Pros",
        "The Definition Dons",
        "Lexicon Legends",
        "The Swift Speakers",
        "Clue Captains",
        "Word Wizards",
        "The Sentence Smashers",
        "The Phrase Phantoms",
        "Express-o-matics"
    ]
    
    static let wordList: [String] = [
        "Apple",
        "Tiger",
        "Beach",
        "Guitar",
        "Pizza",
        "Bicycle",
        "Moon",
        "Chocolate",
        "Doctor",
        "Robot",
        "Castle",
        "Ice Cream",
        "Soccer",
        "Telephone",
        "Unicorn",
        "Superhero",
        "Train",
        "Dinosaur",
        "Wizard",
        "Jungle",
        "Elephant",
        "Skyscraper",
        "Penguin",
        "Mountain",
        "Computer",
        "Parrot",
        "Rainbow",
        "Magic",
        "Ocean",
        "Balloon",
        "Candy",
        "Firefighter",
        "Pumpkin",
        "Fairy",
        "Koala",
        "Hiking",
        "Dragon",
        "Astronaut",
        "Ninja",
        "Castle",
        "Mermaid",
        "Crab",
        "Marshmallow",
        "Squirrel",
        "Piano",
        "Turtle",
        "Hurricane",
        "Vampire",
        "Buffalo",
        "Whale",
        "Cactus",
        "Lighthouse",
        "Galaxy",
        "Frog",
        "Gazelle",
        "Volcano",
        "Giraffe",
        "Trampoline",
        "Cinderella",
        "Football",
        "Sailboat",
        "Sandwich",
        "Snowman",
        "Butterfly",
        "Pineapple",
        "Lemonade",
        "Kangaroo",
        "Football",
        "Taco",
        "Octopus",
        "Seahorse",
        "Scarecrow",
        "Gumball",
        "Jellyfish",
        "Windmill",
        "Chestnut",
        "Cereal",
        "Gecko",
        "Tractor",
        "Banana",
        "Acorn",
        "Tornado",
        "Walrus",
        "Teapot",
        "Puppy",
        "Kite",
        "Sprinkles",
        "Yacht",
        "Chameleon",
        "Toucan",
        "Crown",
        "Fountain",
        "Iceberg",
        "Teddy Bear",
        "Grapes",
        "Skiing",
        "Starfish",
        "Acrobat",
        "Crayon",
        "Treasure",
        "Pocket",
        "Fortune",
        "Waffle"
    ]
}
